local neotree = {
	-- "nvim-neo-tree/neo-tree.nvim",
	-- branch = "v3.x",
	-- opts = {
	-- 	sync_root_with_cwd = true,
	-- 	respect_buf_cwd = true,
	-- 	update_focused_file = {
	-- 		enable = true,
	-- 		update_root = true,
	-- 	},
	-- 	close_if_last_window = true,
	-- 	filesystem = {
	-- 		filtered_items = {
	-- 			visible = true,
	-- 			hide_dotfiles = false,
	-- 			hide_gitignored = false,
	-- 			hide_by_name = {
	-- 				".github",
	-- 				".gitignore",
	-- 				"package-lock.json",
	-- 			},
	-- 			never_show = { ".git" },
	-- 		},
	-- 	},
	-- },
	-- dependencies = {
	-- 	"nvim-lua/plenary.nvim",
	-- 	"nvim-tree/nvim-web-devicons", -- not strictly required, but recommended
	-- 	"MunifTanjim/nui.nvim",
	-- 	"3rd/image.nvim", -- Optional image support in preview window: See `# Preview Mode` for more information
	-- },
}

-- vim.keymap.set("n", "<C-e>", function()
-- 	if is_tree_open then
-- 		is_tree_open = false
-- 		require("neo-tree.command").execute({
-- 			action = "close",
-- 		})
--
-- 		return
-- 	end
--
-- 	full_path = vim.fn.getcwd()
-- 	-- under_proj = is_path_contained_under(full_path, PROJ_DIR)
-- 	if not under_proj then
-- 		full_path = vim.fn.getcwd()
-- 	end
--
-- 	is_tree_open = true
-- 	require("neo-tree.command").execute({
-- 		action = "focus",
-- 		source = "filesystem",
-- 		position = "right",
-- 		reveal_file = full_path, -- path to file or folder to reveal
-- 		reveal_force_cwd = true, -- change cwd without asking if needed
-- 	})
-- end, { desc = "Open neo-tree at nvim process start directory", noremap = true })

return neotree
